App\Entity\Repair:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
  properties:
    customer:
      - Valid: ~
      - NotBlank: ~
      - NotNull: ~
    category:
      - Valid: ~
      - NotBlank: ~
      - NotNull: ~
    status:
      - Valid: ~
      - NotBlank: ~
      - NotNull: ~
    products:
      - App\Validator\Quantity\QuantityLessThanAmount: ~
      - App\Validator\Quantity\QuantityPositive: ~
      - App\Validator\Quantity\QuantityNonZero: ~
      - App\Validator\Quantity\QuantityNotEmpty: ~
    code:
      - NotBlank: ~
      - NotNull: ~
      - Length:
          min: 13
          max: 13
    imei:
      - Type: integer
      - Length:
          min: 17
          max: 17
    fault:
      - NotBlank: ~
      - NotNull: ~
    colour:
      - Length:
          min: 7
          max: 7
    labourPrice:
      - Type: float
    tax:
      - Type: float
    visible:
      - Type: bool

App\Entity\Category:
  properties:
    name:
      - NotBlank: ~
      - NotNull: ~

App\Entity\Customer:
  properties:
    fullname:
      - NotBlank: ~
      - NotNull: ~
    email:
      - Email: ~
      - Length:
          max: 70
    zipCode:
      - Type: integer
      - Length:
          min: 5
          max: 5
    phone:
      - NotBlank: ~
      - NotNull: ~
      - Type: integer
      - Length:
          min: 9
          max: 9

App\Entity\Product:
  properties:
    name:
      - NotBlank: ~
      - NotNull: ~
    amount:
      - Type: integer
    price:
      - Type: float

App\Entity\RepairHasProducts:
  properties:
    quantity:
      - Type: integer

App\Entity\Status:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
  properties:
    name:
      - NotBlank: ~
      - NotNull: ~
    colour:
      - Length:
          min: 7
          max: 7

App\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
  properties:
    username:
      - NotBlank: ~
      - NotNull: ~
    email:
      - Email: ~
    password:
      - NotBlank: ~
      - NotNull: ~
      - NotCompromisedPassword: ~
