App\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: App\Repository\CustomerRepository
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        fullname:
            type: string
            scale: 0
            length: 70
            unique: false
            nullable: false
            precision: 0
        address:
            type: string
            scale: 0
            length: 70
            unique: false
            nullable: true
            precision: 0
        city:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: true
            precision: 0
        email:
            type: string
            scale: 0
            length: 70
            unique: false
            nullable: true
            precision: 0
        zipCode:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: zip_code
        phone:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        modified:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        created:
            type: datetime_immutable
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
