App\Entity\Product:
    type: entity
    table: product
    repositoryClass: App\Repository\ProductRepository
    id:
        id:
            type: uuid
    fields:
        name:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: false
            precision: 0
        amount:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        price:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        modified:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        created:
            type: datetime_immutable
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
