App\Entity\RepairHasProducts:
  type: entity
  table: repair_products
  id:
    id:
      type: uuid
  fields:
    quantity:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
    created:
      type: datetime_immutable
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
  manyToOne:
    repair:
      targetEntity: App\Entity\Repair
      inversedBy: products
      cascade: [ persist ]
      joinColumn:
        name: repair
        referencedColumnName: id
        nullable: false
    product:
      targetEntity: App\Entity\Product
      cascade: [ persist ]
      joinColumn:
        name: product
        referencedColumnName: id
        nullable: false
  lifecycleCallbacks: {  }
