App\Entity\Repair:
  type: entity
  table: repair
  repositoryClass: App\Repository\RepairRepository
  id:
    id:
      type: uuid
  fields:
    code:
      type: string
      scale: 0
      length: 16
      unique: true
      nullable: false
      precision: 0
    imei:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
    pattern:
      type: string
      scale: 0
      length: 20
      unique: false
      nullable: true
      precision: 0
    fault:
      type: string
      scale: 0
      length: 85
      unique: false
      nullable: false
      precision: 0
    colour:
      type: string
      scale: 0
      length: 50
      unique: false
      nullable: true
      precision: 0
    privateComment:
      type: string
      scale: 0
      length: 200
      unique: false
      nullable: true
      precision: 0
    publicComment:
      type: string
      scale: 0
      length: 200
      unique: false
      nullable: true
      precision: 0
    labourPrice:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
    tax:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: true
      precision: 0
    visible:
      type: integer
      scale: 0
      length: 50
      unique: false
      nullable: false
      precision: 0
    modified:
      type: datetime
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
    created:
      type: datetime_immutable
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
  manyToOne:
    customer:
      targetEntity: App\Entity\Customer
      mappedBy: id
      cascade: [ persist ]
    category:
      targetEntity: App\Entity\Category
      mappedBy: id
      cascade: [ persist ]
    status:
      targetEntity: App\Entity\Status
      mappedBy: id
      cascade: [ persist ]
  oneToMany:
    products:
      targetEntity: App\Entity\Product
      orphanRemoval: true
      mappedBy: repair
  lifecycleCallbacks: {  }
