App\Entity\Status:
    type: entity
    table: status
    repositoryClass: App\Repository\StatusRepository
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        name:
            type: string
            scale: 0
            length: 25
            unique: true
            nullable: false
            precision: 0
        colour:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: true
            precision: 0
        modified:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        created:
            type: datetime_immutable
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
