App\Entity\User:
    type: entity
    table: user
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: uuid
    fields:
        username:
            type: string
            scale: 0
            length: 15
            unique: true
            nullable: false
            precision: 0
        email:
            type: string
            scale: 0
            length: 70
            unique: false
            nullable: true
            precision: 0
        password:
            type: string
            scale: 0
            length: 100
            unique: false
            nullable: false
            precision: 0
        lastSession:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: last_session
        modified:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        created:
            type: datetime_immutable
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
